<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="GenericRecognition.Workbench.Abstractions" Version="[0.1.16]" />
    <PackageReference Include="GenericRecognition.Workbench.Wpf" Version="[0.1.16]" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

</Project>
